import yaml

def get_config():
    with open("config.yaml") as f:
        config = yaml.safe_load(f)
    return config

CONFIG = get_config()
# Repos List
GH_REPOS = CONFIG["GH_REPO"]
# GitHub Sponsors
GH_TOKEN = CONFIG["GH_SPONSORS"]["GH_TOKEN"]
GH_SPONSORS_TIER_ID = CONFIG["GH_SPONSORS"]["GH_SPONSORS_TIER_ID"]
GH_SPONSORS_ROLE_ID = CONFIG["GH_SPONSORS"]["GH_SPONSORS_ROLE_ID"]["define"]
GH_OVERRIDE_ROLE_ID = CONFIG["GH_SPONSORS"]["GH_OVERRIDE_ROLE_ID"]["define"]
# Discord Bot
BOT_TOKEN = CONFIG["DISCORD_BOT"]["BOT_TOKEN"]
GUILD_ID = CONFIG["DISCORD_BOT"]["GUILD_ID"]
REDIRECT_URI = CONFIG["DISCORD_BOT"]["REDIRECT_URI"]
CLIENT_ID = CONFIG["DISCORD_BOT"]["CLIENT_ID"]
CLIENT_SECRET = CONFIG["DISCORD_BOT"]["CLIENT_SECRET"]
# Discord Roles
ROLES_CHANNEL_ID = CONFIG["DISCORD_ROLES"]["ROLES_CHANNEL_ID"]
ROLES_MESSAGE_ID = CONFIG["DISCORD_ROLES"]["ROLES_MESSAGE_ID"]
REQUIRED_ROLES = CONFIG["DISCORD_ROLES"]["REQUIRED_ROLES"]
