FROM python:3.12@sha256:cd7c412d000912f29075a1b8803e43cb2f38bb67f104019df526df5ceaf30569

WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY db.py db.py
COPY web.py web.py
COPY config.py config.py

CMD ["python", "-u", "web.py"]