FROM python:3.12-alpine3.20

WORKDIR /app

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# DB
COPY db.py db.py
ADD dbschema dbschema
COPY edgedb.toml edgedb.toml

# Bot
COPY main.py main.py
COPY gh.py gh.py
COPY web.py web.py
COPY config.py config.py

CMD ["python", "-u", "main.py"]