services:
  web:
    image: ghcr.io/nelsondane/sponsors-bot-web:latest
    container_name: web
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - EDGEDB_DSN=edgedb://edgedb:5656?tls_security=insecure
    ports:
      - 8080:8080
    depends_on:
      - edgedb

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    restart: always
    command: tunnel run --token ${CLOUDFLARE_TOKEN}

  bot:
    image: ghcr.io/nelsondane/sponsors-bot:latest
    container_name: bot
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - EDGEDB_DSN=edgedb://edgedb:5656?tls_security=insecure
    depends_on:
      - edgedb

  edgedb:
    image: edgedb/edgedb:latest
    container_name: edgedb
    restart: always
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
      - EDGEDB_SERVER_ADMIN_UI=enabled
      - EDGEDB_SERVER_BIND_ADDRESS=0.0.0.0
    volumes:
      - ./config/edgedb:/var/lib/edgedb/data
      - ./dbschema:/dbschema
    ports:
      - 5656:5656

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_POLL_INTERVAL=3600
    command:
      - edgedb
      - bot
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
