FROM python:3.12

WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Bot
COPY db.py db.py
COPY main.py main.py
COPY gh.py gh.py
COPY web.py web.py
COPY config.py config.py

CMD ["python", "-u", "main.py"]