FROM python:3.12-alpine3.20

WORKDIR /app

RUN apk add --no-cache gcc musl-dev linux-headers

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY db.py db.py
COPY web.py web.py
COPY config.py config.py

CMD ["python", "-u", "web.py"]